#!/usr/bin/env bash
#
# Copyright 2019 Yan Shen (aka 石头), all rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Wrapper script for downloading and running specific bazel version

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
RESET=$(tput sgr0)

REPOSITORY_ROOT=$(git rev-parse --show-toplevel)

BAZEL_VERSION=$(cat $REPOSITORY_ROOT/.bazelversion)
PLATFORM=$(uname | tr '[:upper:]' '[:lower:]')
BAZEL_BINARY_URL="https://releases.bazel.build/$BAZEL_VERSION/release/bazel-$BAZEL_VERSION-$PLATFORM-x86_64"
BAZEL_BINARY="$HOME/.pumpkin/bazel-$BAZEL_VERSION"

if [[ "$PLATFORM" != "darwin" ]] && [[ "$PLATFORM" != "linux" ]]; then
  echo "$RED[!] bazel wrapper cannot download a binary for $PLATFORM""$RESET"
  exit 1
fi

if [[ ! -x ${BAZEL_BINARY} ]]; then
  echo "$GREEN""Downloading bazel binary""$RESET"
  rm -f $(dirname ${BAZEL_BINARY})/bazel*
  mkdir -p $(dirname ${BAZEL_BINARY})
  wget ${BAZEL_BINARY_URL} --output-document ${BAZEL_BINARY}
  chmod +x ${BAZEL_BINARY}
fi

${BAZEL_BINARY} "$@"
exit $?
