#!/usr/bin/env bash
#
# Copyright 2019 Yan Shen (aka 石头), all rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# download android sdk
RED=$(tput setaf 1)
RESET=$(tput sgr0)

if [[ -z "$ANDROID_HOME" ]]; then
  export ANDROID_HOME=$HOME/android_sdk/
fi

DOWNLOAD_COMMAND=wget
if [[ ! -x "$(command -v ${DOWNLOAD_COMMAND})" ]]; then
  DOWNLOAD_COMMAND="curl -LO"
fi

if [[ ! -x "$(command -v ${DOWNLOAD_COMMAND})" ]]; then
  echo "$(tput setaf 1)No wget or curl found$(tput sgr0)"
  exit 1
fi

URL_BASE="https://dl.google.com/android/repository/"

platform=$(uname)
if [[ "$platform" == "Darwin" ]]; then
  FILENAME="sdk-tools-darwin-4333796.zip"
  PROFILE_FILE="$HOME/.bash_profile"
elif [[ "$platform" == "Linux" ]]; then
  FILENAME="sdk-tools-linux-4333796.zip"
  PROFILE_FILE="$HOME/.bashrc"
else
  echo "Android SDK does not have an archive for $platform"
  exit 1
fi

if [[ ! -d "$ANDROID_HOME" ]]; then
  ${DOWNLOAD_COMMAND} ${URL_BASE}/${FILENAME}
  unzip ${FILENAME} -d ${ANDROID_HOME}
  while read p; do echo "y" | ${ANDROID_HOME}/tools/bin/sdkmanager "${p}" > /dev/null; done < tools/android_requirement.txt
  echo "Removing $(rm -v ${FILENAME})"
fi

echo "Android SDK at $RED$ANDROID_HOME$RESET"
echo "Run$RED 'export ANDROID_HOME=$ANDROID_HOME'$RESET before building"
echo "Run$RED 'echo export ANDROID_HOME=$ANDROID_HOME >> $PROFILE_FILE'$RESET to persist the setting"
